import pygame

# Action Indices
# See ship_tasks.py for a list of the actions

ACTION_ZERO = 0
ACTION_ONE = 1
ACTION_BUILD_CITY = 2
ACTION_DEVELOP = 3
ACTION_COLONISE = 4
ACTION_COLLECT_BIOMASS = 5
ACTION_TERRAFORM = 6
ACTION_COLLECT = 7
ACTION_SELL_RED = 8
ACTION_SELL_GREEN = 9
ACTION_SELL_BLUE = 10
ACTION_SELL_CYAN = 11
ACTION_SELL_MAGENTA = 12
ACTION_SELL_YELLOW = 13
ACTION_SELL_ARTIFACT = 14
ACTION_BUY_BUILDING = 15

# Key Controls
ACTION_KEYCONTROL_DICT = {
    pygame.K_y: ACTION_BUILD_CITY,
    pygame.K_d: ACTION_DEVELOP,
    pygame.K_c: ACTION_COLONISE,
    pygame.K_b: ACTION_COLLECT_BIOMASS,
    pygame.K_t: ACTION_TERRAFORM,
    pygame.K_m: ACTION_COLLECT,
    pygame.K_l: ACTION_BUY_BUILDING,
    pygame.K_a: ACTION_SELL_ARTIFACT,
    pygame.K_1: ACTION_SELL_RED,
    pygame.K_2: ACTION_SELL_GREEN,
    pygame.K_3: ACTION_SELL_BLUE,
    pygame.K_4: ACTION_SELL_CYAN,
    pygame.K_5: ACTION_SELL_MAGENTA,
    pygame.K_6: ACTION_SELL_YELLOW
}
